Repository meteroid-oss/meteroid, pull requests merged in 2024-03, with the labels that each got.

#124 feat: Subscription cancellation
  modules/meteroid/crates/meteroid-repository/queries/stats.sql
  modules/meteroid/crates/meteroid-repository/queries/subscriptions.sql
  modules/meteroid/crates/meteroid-repository/refinery/migrations/V0032__subscription_cancelation.sql
  modules/meteroid/crates/meteroid-repository/src/cornucopia.rs
  modules/meteroid/proto/api/subscriptions/v1/models.proto
  modules/meteroid/proto/api/subscriptions/v1/subscriptions.proto
  modules/meteroid/src/adapters/stripe.rs
  modules/meteroid/src/api/services/subscriptions/mapping.rs
  modules/meteroid/src/api/services/subscriptions/service.rs
  modules/meteroid/src/compute/clients/subscription.rs
  modules/meteroid/src/compute/invoice_engine.rs
  modules/meteroid/src/datetime.rs
  modules/meteroid/src/eventbus/analytics_handler.rs
  modules/meteroid/src/eventbus/webhook_handler.rs
  modules/meteroid/src/lib.rs
  modules/meteroid/src/mapping/common.rs
  modules/meteroid/src/services/mod.rs
  modules/meteroid/src/services/subscription/ext.rs
  modules/meteroid/src/services/subscription/mod.rs
  modules/meteroid/src/workers/invoicing/shared/update_invoice_line_items.rs
  modules/meteroid/tests/integration/test_basic.rs
  modules/meteroid/tests/integration/test_subscription.rs
Labels: feature

#123 feat(error processing): logging 'source' in gRPC -> HTTP tower conversation
  Cargo.toml
  crates/common-grpc-error-as-tonic-macros-impl/Cargo.toml
  crates/common-grpc-error-as-tonic-macros-impl/src/lib.rs
  crates/common-grpc-error-as-tonic-macros/Cargo.toml
  crates/common-grpc-error-as-tonic-macros/src/lib.rs
  crates/common-grpc/Cargo.toml
  crates/common-grpc/src/middleware/server/error_logger/layer.rs
  crates/common-grpc/src/middleware/server/error_logger/mod.rs
  crates/common-grpc/src/middleware/server/mod.rs
  modules/meteroid/Cargo.toml
  modules/meteroid/src/api/server.rs
  modules/meteroid/src/api/services/customers/error.rs
  modules/meteroid/src/api/services/customers/mod.rs
  modules/meteroid/src/api/services/customers/service.rs
Labels: feature

#125 refactor(customers): use thiserror
  modules/meteroid/src/api/services/customers/error.rs
  modules/meteroid/src/api/services/customers/service.rs
Labels: chore

#136 feat(analytics): added country information in events
  modules/meteroid/src/api/server.rs
  modules/meteroid/src/bin/server.rs
  modules/meteroid/src/eventbus/analytics_handler.rs
  modules/meteroid/src/eventbus/mod.rs
Labels: feature

#137 chore: Send analytics event on subscription cancellation
  modules/meteroid/src/api/subscriptions/service.rs
  modules/meteroid/src/eventbus/analytics_handler.rs
  modules/meteroid/src/eventbus/mod.rs
Labels: chore

#134 feat(subscription): Create subscription first part
  modules/meteroid/crates/meteroid-repository/queries/plans.sql
  modules/meteroid/crates/meteroid-repository/src/cornucopia.rs
  modules/meteroid/proto/api/plans/v1/models.proto
  modules/meteroid/proto/api/plans/v1/plans.proto
  modules/meteroid/src/api/plans/mapping.rs
  modules/web/packages/ui/src/components/Command/Command.tsx
  modules/web/packages/ui/src/components/Command/index.ts
  modules/web/packages/ui/src/components/Dialog/Dialog.tsx
  modules/web/packages/ui/src/components/Dialog/index.ts
  modules/web/packages/ui/src/components/index.ts
  modules/web/web-app/components/layouts/shared/PageSection.tsx
  modules/web/web-app/features/billing/plans/PlanSelect.tsx
  modules/web/web-app/features/billing/plans/create/details/DetailsForm.tsx
  modules/web/web-app/features/billing/plans/pricecomponents/EditPriceComponentCard.tsx
  modules/web/web-app/features/billing/plans/pricecomponents/PriceComponentOverview.tsx
  modules/web/web-app/features/customers/CustomerSelect.tsx
  modules/web/web-app/features/subscriptions/SubscriptionsHeader.tsx
  modules/web/web-app/pages/tenants/subscription/subscriptionCreate.tsx
  modules/web/web-app/pages/tenants/subscription/subscriptions.tsx
  modules/web/web-app/router/tenant/index.tsx
  modules/web/web-app/router/tenant/subscriptions.tsx
Labels: feature

#149 feat(subscription): Create subscription wizard
  modules/meteroid/crates/meteroid-repository/queries/plans.sql
  modules/meteroid/crates/meteroid-repository/src/cornucopia.rs
  modules/meteroid/proto/api/plans/v1/models.proto
  modules/meteroid/proto/api/plans/v1/plans.proto
  modules/meteroid/src/api/plans/mapping.rs
  modules/meteroid/src/api/plans/service.rs
  modules/web/packages/ui/src/components/form/generic-form-field.tsx
  modules/web/packages/ui/src/components/ui/date-picker.tsx
  modules/web/packages/ui/src/components/ui/index.ts
  modules/web/web-app/features/billing/plans/PlanSelect.tsx
  modules/web/web-app/features/billing/plans/SubscribablePlanVersionSelect.tsx
  modules/web/web-app/features/billing/plans/pricecomponents/PriceComponentOverview.tsx
  modules/web/web-app/pages/tenants/subscription/create/StepPlanAndCustomer.tsx
  modules/web/web-app/pages/tenants/subscription/create/StepSettings.tsx
  modules/web/web-app/pages/tenants/subscription/create/state.ts
  modules/web/web-app/pages/tenants/subscription/subscriptionCreate.tsx
  modules/web/web-app/router/tenant/billing.tsx
  modules/web/web-app/router/tenant/subscriptions.tsx
Labels: feature

#151 chore: Update rust version to latest stable 1.77 version
  Cargo.toml
Labels: dependencies, chore

#153 fix: set release profile
  .github/workflows/docker.yaml
Labels: bug, skip-changelog

#157 chore: update-readme
  README.md
  assets/meteroid-schema-4.webp
Labels: chore
