Repository meteroid-oss/meteroid, pull requests merged in 2024-10, with the labels that each got.

#347 chore(deps): upgraded tonic / axum / prost / opentelemetry / http / http_body / etc
  .github/dependabot.yml
  Cargo.toml
  crates/common-grpc/src/middleware/server/auth/mod.rs
  modules/metering/crates/metering-grpc/build.rs
  modules/metering/src/server.rs
  modules/meteroid/Cargo.toml
  modules/meteroid/crates/meteroid-grpc/build.rs
  modules/meteroid/src/api/axum_routers/webhook_in_router.rs
  modules/meteroid/src/api/axum_server.rs
  modules/meteroid/src/api/billablemetrics/service.rs
  modules/meteroid/src/api/server.rs
Labels: dependencies, rust

#348 feat: Subscription coupons
  CONTRIBUTING.md
  modules/meteroid/crates/diesel-models/src/errors.rs
  modules/meteroid/crates/diesel-models/src/lib.rs
  modules/meteroid/crates/diesel-models/src/query/coupons.rs
  modules/meteroid/crates/diesel-models/src/query/mod.rs
  modules/meteroid/crates/diesel-models/src/query/subscription_coupons.rs
  modules/meteroid/crates/diesel-models/src/schema.rs
  modules/meteroid/crates/diesel-models/src/subscription_coupons.rs
  modules/meteroid/crates/meteroid-store/src/domain/coupons.rs
  modules/meteroid/crates/meteroid-store/src/domain/historical_rates.rs
  modules/meteroid/crates/meteroid-store/src/domain/mod.rs
  modules/meteroid/crates/meteroid-store/src/domain/subscription_coupons.rs
  modules/meteroid/crates/meteroid-store/src/domain/subscriptions.rs
  modules/meteroid/crates/meteroid-store/src/repositories/historical_rates.rs
  modules/meteroid/crates/meteroid-store/src/repositories/subscriptions.rs
  modules/meteroid/migrations/diesel/2024-09-29-142325_subscription_coupons/down.sql
  modules/meteroid/migrations/diesel/2024-09-29-142325_subscription_coupons/up.sql
  modules/meteroid/proto/api/subscriptions/v1/models.proto
  modules/meteroid/src/api/coupons/mapping.rs
  modules/meteroid/src/api/coupons/mod.rs
  modules/meteroid/src/api/subscriptions/mapping.rs
  modules/meteroid/src/bin/server.rs
  modules/meteroid/src/migrations.rs
  modules/meteroid/src/seeder/runner.rs
  modules/meteroid/tests/integration/e2e.rs
  modules/meteroid/tests/integration/meteroid_it/container.rs
Labels: feature

#363 fix: Add log feature to tracing crate
  Cargo.toml
Labels: bug

#365 chore: fix cyclic imports preventing HMR in frontend
  modules/web/pnpm-lock.yaml
  modules/web/web-app/.eslintrc.js
  modules/web/web-app/App.tsx
  modules/web/web-app/features/auth/components/LoginForm.tsx
  modules/web/web-app/features/auth/components/RegistrationForm.tsx
  modules/web/web-app/features/auth/sessionRoutes.tsx
  modules/web/web-app/features/billing/plans/pricecomponents/EditPriceComponent.tsx
  modules/web/web-app/features/billing/plans/pricecomponents/EditPriceComponentCard.tsx
  modules/web/web-app/features/billing/plans/pricecomponents/PriceComponentSection.tsx
  modules/web/web-app/features/billing/plans/pricecomponents/atoms.ts
  modules/web/web-app/features/billing/plans/pricecomponents/components/CapacityForm.tsx
  modules/web/web-app/features/billing/plans/pricecomponents/components/OneTimeForm.tsx
  modules/web/web-app/features/billing/plans/pricecomponents/components/RecurringForm.tsx
  modules/web/web-app/features/billing/plans/pricecomponents/components/SlotsForm.tsx
  modules/web/web-app/features/billing/plans/pricecomponents/components/SubscriptionRateForm.tsx
  modules/web/web-app/features/billing/plans/pricecomponents/components/UsageBasedForm.tsx
  modules/web/web-app/features/billing/plans/pricecomponents/components/shared.ts
  modules/web/web-app/lib/connectrpc-interceptors.ts
  modules/web/web-app/lib/connectrpc.ts
Labels: chore

#366 chore: only run rust CI if rust code changes
  .github/workflows/ci-rust.yaml
Labels: chore

#376 feat: Apply coupons
  Cargo.toml
  modules/meteroid/crates/diesel-models/src/applied_coupons.rs
  modules/meteroid/crates/diesel-models/src/coupons.rs
  modules/meteroid/crates/diesel-models/src/invoices.rs
  modules/meteroid/crates/diesel-models/src/lib.rs
  modules/meteroid/crates/diesel-models/src/query/applied_coupons.rs
  modules/meteroid/crates/diesel-models/src/query/coupons.rs
  modules/meteroid/crates/diesel-models/src/query/invoices.rs
  modules/meteroid/crates/diesel-models/src/query/mod.rs
  modules/meteroid/crates/diesel-models/src/query/subscription_coupons.rs
  modules/meteroid/crates/diesel-models/src/schema.rs
  modules/meteroid/crates/diesel-models/src/subscription_coupons.rs
  modules/meteroid/crates/meteroid-store/Cargo.toml
  modules/meteroid/crates/meteroid-store/src/compute/engine/invoice.rs
  modules/meteroid/crates/meteroid-store/src/domain/coupons.rs
  modules/meteroid/crates/meteroid-store/src/domain/invoices.rs
  modules/meteroid/crates/meteroid-store/src/domain/subscription_coupons.rs
  modules/meteroid/crates/meteroid-store/src/domain/subscriptions.rs
  modules/meteroid/crates/meteroid-store/src/repositories/customers.rs
  modules/meteroid/crates/meteroid-store/src/repositories/invoices.rs
  modules/meteroid/crates/meteroid-store/src/repositories/subscriptions.rs
  modules/meteroid/crates/meteroid-store/src/repositories/tenants.rs
  modules/meteroid/crates/meteroid-store/src/utils/decimals.rs
  modules/meteroid/migrations/diesel/2024-10-12-160006_applied_coupons/down.sql
  modules/meteroid/migrations/diesel/2024-10-12-160006_applied_coupons/up.sql
  modules/meteroid/proto/api/coupons/v1/coupons.proto
  modules/meteroid/proto/api/coupons/v1/models.proto
  modules/meteroid/proto/api/subscriptions/v1/models.proto
  modules/meteroid/src/api/coupons/service.rs
  modules/meteroid/src/api/subscriptions/mapping.rs
  modules/meteroid/src/seeder/runner.rs
  modules/meteroid/tests/integration/test_coupon.rs
Labels: feature, work in progress

#380 feat: Improve plan & price component management (FE)
  modules/meteroid/crates/diesel-models/src/plans.rs
  modules/meteroid/crates/diesel-models/src/query/plans.rs
  modules/meteroid/crates/meteroid-store/src/domain/plans.rs
  modules/meteroid/crates/meteroid-store/src/utils/local_id.rs
  modules/meteroid/proto/api/plans/v1/models.proto
  modules/meteroid/proto/api/plans/v1/plans.proto
  modules/meteroid/src/api/plans/service.rs
  modules/meteroid/tests/integration/test_plan.rs
  modules/web/packages/ui/src/components/ui/input.tsx
  modules/web/packages/ui/src/components/ui/scroll-area.tsx
  modules/web/web-app/components/FamilyPicker/FamilyPicker.tsx
  modules/web/web-app/components/form/PriceInput.tsx
  modules/web/web-app/components/layouts/shared/LayoutHeader/TenantDropdown.tsx
  modules/web/web-app/features/billing/plans/PlanCreateInitModal.tsx
  modules/web/web-app/features/billing/plans/PlansHeader.tsx
  modules/web/web-app/features/billing/plans/PlansTable.tsx
  modules/web/web-app/features/billing/plans/create/details/DetailsForm.tsx
  modules/web/web-app/features/billing/plans/create/details/DetailsFormModal.tsx
  modules/web/web-app/features/billing/plans/details/BillingPeriodModal.tsx
  modules/web/web-app/features/billing/plans/details/PlanDetails.tsx
  modules/web/web-app/features/billing/plans/pricecomponents/PriceComponentCard.tsx
  modules/web/web-app/features/billing/plans/pricecomponents/components/SubscriptionRateForm.tsx
  modules/web/web-app/features/billing/plans/pricecomponents/utils.ts
  modules/web/web-app/features/billing/plans/pricing/PriceComponentPanel.tsx
  modules/web/web-app/features/billing/plans/trial/PlanTrial.tsx
  modules/web/web-app/features/settings/tabs/InvoiceTab.tsx
  modules/web/web-app/hooks/useQueryState.tsx
  modules/web/web-app/lib/mapping/index.ts
  modules/web/web-app/lib/schemas/plans.ts
  modules/web/web-app/pages/tenants/billing/index.tsx
  modules/web/web-app/pages/tenants/billing/plans.tsx
  modules/web/web-app/router/tenant/catalog.tsx
Labels: feature
