Repository meteroid-oss/meteroid, pull requests merged in 2024-05, with the labels that each got.

#207 chore: use non-deprecated timestamp functions
  modules/meteroid/src/adapters/stripe.rs
  modules/meteroid/src/compute/clients/usage.rs
  modules/meteroid/src/mapping/common.rs
Labels: chore

#208 refactor: naming convention - use sort_by instead of order_by
  modules/meteroid/proto/api/invoices/v1/invoices.proto
  modules/meteroid/proto/api/plans/v1/plans.proto
  modules/meteroid/proto/api/webhooksout/v1/webhooksout.proto
  modules/meteroid/src/api/invoices/service.rs
  modules/meteroid/src/api/plans/service.rs
  modules/meteroid/src/api/webhooksout/service.rs
  modules/meteroid/tests/integration/test_webhooks_out.rs
  modules/web/web-app/features/billing/plans/PlansTable.tsx
  modules/web/web-app/features/customers/cards/InvoicesCard.tsx
  modules/web/web-app/features/dashboard/sections/MrrSection.tsx
  modules/web/web-app/pages/tenants/invoice/Invoices.tsx
Labels: chore

#200 chore: migrate customer to diesel
  modules/meteroid/crates/diesel-models/src/customers.rs
  modules/meteroid/crates/diesel-models/src/extend/order.rs
  modules/meteroid/crates/diesel-models/src/query/customers.rs
  modules/meteroid/crates/diesel-models/src/query/webhooks.rs
  modules/meteroid/crates/meteroid-store/src/domain/customers.rs
  modules/meteroid/crates/meteroid-store/src/domain/misc.rs
  modules/meteroid/crates/meteroid-store/src/repositories/customers.rs
  modules/meteroid/src/api/customers/error.rs
  modules/meteroid/src/api/customers/mapping.rs
  modules/meteroid/src/api/customers/mod.rs
  modules/meteroid/src/api/customers/service.rs
  modules/meteroid/src/api/server.rs
  modules/meteroid/src/workers/invoicing/issue_worker.rs
  modules/meteroid/tests/integration/main.rs
  modules/meteroid/tests/integration/test_customer.rs
Labels: chore

#211 chore: migrate schedules to diesel
  modules/meteroid/crates/diesel-models/src/plan_versions.rs
  modules/meteroid/crates/diesel-models/src/query/plan_versions.rs
  modules/meteroid/crates/diesel-models/src/query/schedules.rs
  modules/meteroid/crates/diesel-models/src/schedules.rs
  modules/meteroid/crates/diesel-models/src/schema.rs
  modules/meteroid/crates/meteroid-store/src/domain/adjustments/discount.rs
  modules/meteroid/crates/meteroid-store/src/domain/adjustments/mod.rs
  modules/meteroid/crates/meteroid-store/src/domain/mod.rs
  modules/meteroid/crates/meteroid-store/src/domain/plans.rs
  modules/meteroid/crates/meteroid-store/src/domain/schedules.rs
  modules/meteroid/crates/meteroid-store/src/repositories/mod.rs
  modules/meteroid/crates/meteroid-store/src/repositories/schedules.rs
  modules/meteroid/crates/meteroid-store/src/repositories/subscriptions.rs
  modules/meteroid/src/api/domain_mapping.rs
  modules/meteroid/src/api/schedules/error.rs
  modules/meteroid/src/api/schedules/mapping.rs
  modules/meteroid/src/api/schedules/mod.rs
  modules/meteroid/src/api/schedules/service.rs
  modules/meteroid/src/api/server.rs
  modules/meteroid/tests/data/2_plans.sql
  modules/meteroid/tests/integration/main.rs
  modules/meteroid/tests/integration/test_schedule.rs
Labels: chore

#216 chore: temporarily ignore failing tests
  modules/meteroid/crates/meteroid-store/src/errors.rs
  modules/meteroid/crates/meteroid-store/src/repositories/users.rs
  modules/meteroid/src/api/users/error.rs
  modules/meteroid/tests/integration/e2e.rs
  modules/meteroid/tests/integration/test_basic.rs
  modules/meteroid/tests/integration/test_customer.rs
  modules/meteroid/tests/integration/test_slot_transaction.rs
  modules/meteroid/tests/integration/test_subscription.rs
  modules/meteroid/tests/integration/test_webhooks_out.rs
  modules/meteroid/tests/integration/test_workers.rs
Labels: chore

#210 refactor: customer API - following naming convention
  modules/meteroid/proto/api/customers/v1/customers.proto
  modules/meteroid/src/api/customers/service.rs
  modules/web/web-app/features/customers/CustomerSelect.tsx
  modules/web/web-app/features/customers/cards/address/EditAddressModal.tsx
  modules/web/web-app/features/customers/cards/balance/EditBalanceModal.tsx
  modules/web/web-app/features/customers/cards/customer/EditCustomerModal.tsx
  modules/web/web-app/pages/tenants/customer/customer.tsx
Labels: chore

#219 chore: migrate billable metric to diesel
  modules/meteroid/crates/diesel-models/src/billable_metrics.rs
  modules/meteroid/crates/diesel-models/src/enums.rs
  modules/meteroid/crates/diesel-models/src/query/billable_metrics.rs
  modules/meteroid/crates/meteroid-store/src/domain/billable_metrics.rs
  modules/meteroid/crates/meteroid-store/src/repositories/billable_metrics.rs
  modules/meteroid/crates/meteroid-store/src/repositories/mod.rs
  modules/meteroid/src/api/billablemetrics/error.rs
  modules/meteroid/src/api/billablemetrics/mapping.rs
  modules/meteroid/src/api/billablemetrics/mod.rs
  modules/meteroid/src/api/billablemetrics/service.rs
  modules/meteroid/src/api/server.rs
  modules/meteroid/src/eventbus/analytics_handler.rs
  modules/meteroid/tests/integration/main.rs
  modules/meteroid/tests/integration/test_billable_metric.rs
Labels: chore

#222 fix: sending event on customer(s) creation
  modules/meteroid/crates/meteroid-store/Cargo.toml
  modules/meteroid/crates/meteroid-store/src/repositories/customers.rs
Labels: bug

#223 feat: log on error on publishing event
  modules/meteroid/src/eventbus/memory.rs
Labels: feature

#225 refactor: api errors
  modules/meteroid/src/api/apitokens/error.rs
  modules/meteroid/src/api/billablemetrics/error.rs
  modules/meteroid/src/api/customers/error.rs
  modules/meteroid/src/api/pricecomponents/error.rs
  modules/meteroid/src/api/productfamilies/error.rs
  modules/meteroid/src/api/productitems/error.rs
  modules/meteroid/src/api/schedules/error.rs
  modules/meteroid/src/api/subscriptions/error.rs
  modules/meteroid/src/api/tenants/error.rs
  modules/meteroid/src/api/users/error.rs
  modules/meteroid/src/api/webhooksout/error.rs
Labels: chore

#228 chore: migrate invoice to diesel
  modules/meteroid/crates/diesel-models/src/invoices.rs
  modules/meteroid/crates/diesel-models/src/query/invoices.rs
  modules/meteroid/crates/diesel-models/src/schema.rs
  modules/meteroid/crates/meteroid-store/src/domain/invoices.rs
  modules/meteroid/crates/meteroid-store/src/repositories/invoices.rs
  modules/meteroid/src/api/invoices/error.rs
  modules/meteroid/src/api/invoices/mapping.rs
  modules/meteroid/src/api/invoices/mod.rs
  modules/meteroid/src/api/invoices/service.rs
  modules/meteroid/src/api/server.rs
  modules/meteroid/src/api/tenants/error.rs
Labels: chore

#233 chore: update draft worker and fix text
  modules/meteroid/crates/diesel-models/Cargo.toml
  modules/meteroid/crates/diesel-models/src/extend/cursor_pagination.rs
  modules/meteroid/crates/diesel-models/src/query/subscriptions.rs
  modules/meteroid/crates/diesel-models/src/schema.rs
  modules/meteroid/crates/diesel-models/src/subscriptions.rs
  modules/meteroid/crates/meteroid-store/src/domain/enums.rs
  modules/meteroid/crates/meteroid-store/src/domain/misc.rs
  modules/meteroid/crates/meteroid-store/src/domain/subscriptions.rs
  modules/meteroid/crates/meteroid-store/src/repositories/subscriptions.rs
  modules/meteroid/src/workers/invoicing/draft_worker.rs
  modules/meteroid/tests/data/0_minimal.sql
  modules/meteroid/tests/data/3_subscriptions.sql
  modules/meteroid/tests/integration/test_workers.rs
Labels: chore

#227 chore: migrate plans to diesel
  modules/meteroid/crates/diesel-models/src/plan_versions.rs
  modules/meteroid/crates/diesel-models/src/plans.rs
  modules/meteroid/crates/diesel-models/src/query/customers.rs
  modules/meteroid/crates/diesel-models/src/query/plan_versions.rs
  modules/meteroid/crates/diesel-models/src/query/plans.rs
  modules/meteroid/crates/diesel-models/src/query/price_components.rs
  modules/meteroid/crates/diesel-models/src/query/schedules.rs
  modules/meteroid/crates/meteroid-repository/src/cornucopia.rs
  modules/meteroid/crates/meteroid-store/src/domain/plans.rs
  modules/meteroid/crates/meteroid-store/src/repositories/plans.rs
  modules/meteroid/src/api/plans/error.rs
  modules/meteroid/src/api/plans/mapping.rs
  modules/meteroid/src/api/plans/mod.rs
  modules/meteroid/src/api/plans/service.rs
  modules/meteroid/src/api/pricecomponents/mapping.rs
  modules/meteroid/src/api/pricecomponents/service.rs
  modules/meteroid/src/api/server.rs
  modules/meteroid/src/api/shared.rs
  modules/meteroid/src/seeder/runner.rs
  modules/meteroid/tests/integration/main.rs
  modules/meteroid/tests/integration/test_plan.rs
Labels: chore

#232 chore: migrate internal to diesel
  modules/meteroid/crates/diesel-models/src/customers.rs
  modules/meteroid/crates/diesel-models/src/query/customers.rs
  modules/meteroid/crates/meteroid-store/src/domain/customers.rs
  modules/meteroid/crates/meteroid-store/src/repositories/customers.rs
  modules/meteroid/src/api/internal/error.rs
  modules/meteroid/src/api/internal/mod.rs
  modules/meteroid/src/api/internal/service.rs
  modules/meteroid/src/api/server.rs
  modules/meteroid/tests/integration/main.rs
  modules/meteroid/tests/integration/test_internal.rs
Labels: chore

#234 chore: migrate instance to diesel
  modules/meteroid/crates/diesel-models/src/organizations.rs
  modules/meteroid/crates/diesel-models/src/query/organizations.rs
  modules/meteroid/crates/diesel-models/src/query/subscriptions.rs
  modules/meteroid/crates/meteroid-repository/src/cornucopia.rs
  modules/meteroid/crates/meteroid-store/src/domain/mod.rs
  modules/meteroid/crates/meteroid-store/src/domain/organizations.rs
  modules/meteroid/crates/meteroid-store/src/repositories/mod.rs
  modules/meteroid/crates/meteroid-store/src/repositories/organizations.rs
  modules/meteroid/crates/meteroid-store/src/repositories/tenants.rs
  modules/meteroid/crates/meteroid-store/src/repositories/users.rs
  modules/meteroid/src/api/instance/error.rs
  modules/meteroid/src/api/instance/mod.rs
  modules/meteroid/src/api/instance/service.rs
  modules/meteroid/src/api/server.rs
  modules/meteroid/tests/integration/main.rs
  modules/meteroid/tests/integration/test_instance.rs
Labels: chore

#235 chore: migrate eventbus to diesel
  modules/meteroid/crates/diesel-models/src/query/price_components.rs
  modules/meteroid/crates/diesel-models/src/webhooks.rs
  modules/meteroid/crates/meteroid-repository/src/cornucopia.rs
  modules/meteroid/crates/meteroid-store/src/domain/enums.rs
  modules/meteroid/crates/meteroid-store/src/domain/webhooks.rs
  modules/meteroid/crates/meteroid-store/src/repositories/price_components.rs
  modules/meteroid/crates/meteroid-store/src/repositories/webhooks.rs
  modules/meteroid/src/api/server.rs
  modules/meteroid/src/bin/server.rs
  modules/meteroid/src/eventbus/analytics_handler.rs
  modules/meteroid/src/eventbus/mod.rs
  modules/meteroid/src/eventbus/webhook_handler.rs
  modules/meteroid/src/singletons.rs
  modules/meteroid/tests/integration/meteroid_it/container.rs
  modules/meteroid/tests/integration/test_webhooks_out.rs
Labels: chore

#243 chore: use diesel in middleware
  crates/common-grpc/Cargo.toml
  crates/common-grpc/src/lib.rs
  crates/common-grpc/src/middleware/server/auth/admin_layer.rs
  crates/common-grpc/src/middleware/server/auth/api_token_validator.rs
  crates/common-grpc/src/middleware/server/auth/mod.rs
  crates/common-grpc/src/middleware/server/auth/strategies/mod.rs
  crates/common-grpc/src/middleware/server/mod.rs
  crates/common-grpc/src/middleware/server/utils.rs
  modules/metering/src/auth.rs
  modules/meteroid/Cargo.toml
  modules/meteroid/crates/diesel-models/src/query/tenants.rs
  modules/meteroid/crates/meteroid-middleware/Cargo.toml
  modules/meteroid/crates/meteroid-middleware/src/lib.rs
  modules/meteroid/crates/meteroid-middleware/src/server/auth/api_layer.rs
  modules/meteroid/crates/meteroid-middleware/src/server/auth/mod.rs
  modules/meteroid/crates/meteroid-middleware/src/server/auth/strategies/api_key_strategy.rs
  modules/meteroid/crates/meteroid-middleware/src/server/auth/strategies/jwt_strategy.rs
  modules/meteroid/crates/meteroid-middleware/src/server/auth/strategies/mod.rs
  modules/meteroid/crates/meteroid-middleware/src/server/mod.rs
  modules/meteroid/crates/meteroid-store/src/domain/enums.rs
  modules/meteroid/crates/meteroid-store/src/repositories/tenants.rs
  modules/meteroid/src/api/server.rs
Labels: chore

#236 chore: Migrate stats to diesel
  modules/meteroid/api.Dockerfile
  modules/meteroid/crates/diesel-models/src/lib.rs
  modules/meteroid/crates/diesel-models/src/query/mod.rs
  modules/meteroid/crates/diesel-models/src/query/slot_transactions.rs
  modules/meteroid/crates/diesel-models/src/query/stats.rs
  modules/meteroid/crates/diesel-models/src/query/subscriptions.rs
  modules/meteroid/crates/diesel-models/src/stats.rs
  modules/meteroid/crates/meteroid-store/src/domain/mod.rs
  modules/meteroid/crates/meteroid-store/src/domain/stats.rs
  modules/meteroid/crates/meteroid-store/src/repositories/mod.rs
  modules/meteroid/crates/meteroid-store/src/repositories/stats.rs
  modules/meteroid/crates/meteroid-store/src/utils/datetime.rs
  modules/meteroid/crates/meteroid-store/src/utils/mod.rs
  modules/meteroid/scheduler.Dockerfile
  modules/meteroid/src/api/server.rs
  modules/meteroid/src/api/shared.rs
  modules/meteroid/src/api/stats/mapping.rs
  modules/meteroid/src/api/stats/mod.rs
  modules/meteroid/src/api/stats/service.rs
  modules/meteroid/src/services/mod.rs
  modules/meteroid/src/services/stats/mod.rs
  modules/meteroid/src/services/stats/stats_service.rs
  modules/meteroid/src/services/stats/utils.rs
  modules/meteroid/tests/integration/main.rs
  modules/meteroid/tests/integration/meteroid_it/clients.rs
  modules/meteroid/tests/integration/test_stats.rs
Labels: chore

#244 chore: cleanup and remove unused imports
  modules/meteroid/crates/diesel-models/src/subscriptions.rs
  modules/meteroid/crates/meteroid-store/src/repositories/organizations.rs
  modules/meteroid/src/api/instance/mod.rs
  modules/meteroid/src/api/server.rs
  modules/meteroid/src/bin/server.rs
  modules/meteroid/src/eventbus/mod.rs
  modules/meteroid/src/eventbus/webhook_handler.rs
  modules/meteroid/tests/integration/meteroid_it/container.rs
Labels: chore

#245 chore: migrate historical rates to diesel
  modules/meteroid/crates/diesel-models/src/bi.rs
  modules/meteroid/crates/diesel-models/src/historical_rates_from_usd.rs
  modules/meteroid/crates/diesel-models/src/lib.rs
  modules/meteroid/crates/diesel-models/src/query/historical_rates_from_usd.rs
  modules/meteroid/crates/diesel-models/src/query/mod.rs
  modules/meteroid/crates/meteroid-store/src/domain/historical_rates.rs
  modules/meteroid/crates/meteroid-store/src/domain/mod.rs
  modules/meteroid/crates/meteroid-store/src/repositories/historical_rates.rs
  modules/meteroid/crates/meteroid-store/src/repositories/mod.rs
  modules/meteroid/src/workers/misc/currency_rates_worker.rs
Labels: chore

#246 chore: migrate to diesel webhook-in api
  crates/common-utils/src/lib.rs
  crates/common-utils/src/uuid.rs
  modules/meteroid/crates/diesel-models/src/query/invoices.rs
  modules/meteroid/crates/diesel-models/src/query/subscriptions.rs
  modules/meteroid/crates/diesel-models/src/query/webhooks.rs
  modules/meteroid/crates/diesel-models/src/webhooks.rs
  modules/meteroid/crates/meteroid-store/src/domain/enums.rs
  modules/meteroid/crates/meteroid-store/src/domain/webhooks.rs
  modules/meteroid/crates/meteroid-store/src/repositories/api_tokens.rs
  modules/meteroid/crates/meteroid-store/src/repositories/invoices.rs
  modules/meteroid/crates/meteroid-store/src/repositories/webhooks.rs
  modules/meteroid/src/adapters/stripe.rs
  modules/meteroid/src/adapters/types.rs
  modules/meteroid/src/bin/server.rs
  modules/meteroid/src/datetime.rs
  modules/meteroid/src/webhook_in_api.rs
  modules/meteroid/tests/integration/e2e.rs
Labels: chore

#247 chore: cleanup draft-worker
  modules/meteroid/crates/meteroid-store/src/domain/customers.rs
  modules/meteroid/crates/meteroid-store/src/domain/enums.rs
  modules/meteroid/crates/meteroid-store/src/domain/invoices.rs
  modules/meteroid/src/workers/invoicing/draft_worker.rs
  modules/meteroid/tests/data/1_customers.sql
  modules/meteroid/tests/integration/e2e.rs
  modules/meteroid/tests/integration/test_workers.rs
Labels: chore

#250 chore: migrate to diesel finalize-worker
  modules/meteroid/crates/diesel-models/src/query/invoices.rs
  modules/meteroid/crates/meteroid-store/src/repositories/invoices.rs
  modules/meteroid/src/api/billablemetrics/mapping.rs
  modules/meteroid/src/workers/invoicing/finalize_worker.rs
  modules/meteroid/src/workers/invoicing/shared/line_items.rs
  modules/meteroid/src/workers/invoicing/shared/mod.rs
  modules/meteroid/tests/integration/e2e.rs
Labels: chore

#251 chore: migrate price_worker to diesel
  modules/meteroid/crates/diesel-models/src/query/invoices.rs
  modules/meteroid/crates/meteroid-store/src/repositories/invoices.rs
  modules/meteroid/src/workers/invoicing/price_worker.rs
  modules/meteroid/src/workers/invoicing/shared/line_items.rs
  modules/meteroid/src/workers/invoicing/shared/mod.rs
  modules/meteroid/tests/integration/e2e.rs
Labels: chore

#252 chore: migrate to diesel issue_worker
  modules/meteroid/crates/diesel-models/src/query/invoices.rs
  modules/meteroid/crates/meteroid-store/src/repositories/invoices.rs
  modules/meteroid/src/adapters/stripe.rs
  modules/meteroid/src/adapters/types.rs
  modules/meteroid/src/api/customers/mapping.rs
  modules/meteroid/src/workers/invoicing/issue_worker.rs
Labels: chore
