Repository meteroid-oss/meteroid, pull requests merged in 2025-04, with the labels that each got.

#552 fix: Fix hubspot client
  Cargo.toml
  modules/meteroid/Cargo.toml
  modules/meteroid/crates/hubspot-client/Cargo.toml
  modules/meteroid/crates/hubspot-client/src/associations.rs
  modules/meteroid/crates/hubspot-client/src/client.rs
  modules/meteroid/crates/hubspot-client/src/companies.rs
  modules/meteroid/crates/hubspot-client/src/deals.rs
  modules/meteroid/crates/hubspot-client/src/error.rs
  modules/meteroid/crates/hubspot-client/src/lib.rs
  modules/meteroid/crates/hubspot-client/src/model.rs
  modules/meteroid/crates/hubspot-client/src/properties.rs
  modules/meteroid/crates/meteroid-oauth/src/service.rs
  modules/meteroid/crates/meteroid-store/src/domain/subscriptions.rs
Labels: bug

#553 feat: Drop gotenberg, add typst & historical rate
  Cargo.toml
  docker/develop/docker-compose.yml
  modules/meteroid/Cargo.toml
  modules/meteroid/crates/diesel-models/src/query/historical_rates_from_usd.rs
  modules/meteroid/crates/meteroid-invoicing/Cargo.toml
  modules/meteroid/crates/meteroid-invoicing/README.md
  modules/meteroid/crates/meteroid-invoicing/assets/base.css
  modules/meteroid/crates/meteroid-invoicing/assets/fonts/Inter-Variable.ttf
  modules/meteroid/crates/meteroid-invoicing/assets/footer-logo.png
  modules/meteroid/crates/meteroid-invoicing/assets/footer.css
  modules/meteroid/crates/meteroid-invoicing/assets/styles.css
  modules/meteroid/crates/meteroid-invoicing/assets/wordmark.svg
  modules/meteroid/crates/meteroid-invoicing/examples/typst_invoices.rs
  modules/meteroid/crates/meteroid-invoicing/l10n/en-US/invoice.ftl
  modules/meteroid/crates/meteroid-invoicing/l10n/fr-FR/invoice.ftl
  modules/meteroid/crates/meteroid-invoicing/package.json
  modules/meteroid/crates/meteroid-invoicing/pnpm-lock.yaml
  modules/meteroid/crates/meteroid-invoicing/src/errors.rs
  modules/meteroid/crates/meteroid-invoicing/src/footer_render.rs
  modules/meteroid/crates/meteroid-invoicing/src/html_render.rs
  modules/meteroid/crates/meteroid-invoicing/src/lib.rs
  modules/meteroid/crates/meteroid-invoicing/src/model.rs
  modules/meteroid/crates/meteroid-invoicing/src/pdf.rs
  modules/meteroid/crates/meteroid-invoicing/src/svg.rs
  modules/meteroid/crates/meteroid-invoicing/src/typst_render.rs
  modules/meteroid/crates/meteroid-invoicing/src/xml_facturx.rs
  modules/meteroid/crates/meteroid-invoicing/tailwind.config.js
  modules/meteroid/crates/meteroid-invoicing/templates/example.typ
  modules/meteroid/crates/meteroid-invoicing/templates/invoice.typ
  modules/meteroid/crates/meteroid-invoicing/templates/main.typ
  modules/meteroid/crates/meteroid-invoicing/templates/template.typ
  modules/meteroid/crates/meteroid-store/src/repositories/historical_rates.rs
  modules/meteroid/src/api/invoices/mod.rs
  modules/meteroid/src/api/invoices/service.rs
  modules/meteroid/src/api/server.rs
  modules/meteroid/src/bin/scheduler.rs
  modules/meteroid/src/bin/seeder.rs
  modules/meteroid/src/bin/server.rs
  modules/meteroid/src/bootstrap/historical_rates.rs
  modules/meteroid/src/bootstrap/mod.rs
  modules/meteroid/src/config.rs
  modules/meteroid/src/constants.rs
  modules/meteroid/src/lib.rs
  modules/meteroid/src/services/invoice_rendering.rs
  modules/meteroid/src/workers/misc/currency_rates_worker.rs
  modules/meteroid/tests/integration/meteroid_it/config.rs
Labels: feature

#554 feat: Add hubspot_sync queue and dequeuer
  .github/workflows/ci-rust.yaml
  Cargo.toml
  crates/common-domain/src/pgmq/mod.rs
  crates/common-logging/src/unwrapper.rs
  modules/meteroid/Cargo.toml
  modules/meteroid/crates/diesel-models/src/connectors.rs
  modules/meteroid/crates/diesel-models/src/customers.rs
  modules/meteroid/crates/diesel-models/src/enums.rs
  modules/meteroid/crates/diesel-models/src/extend/connection_metadata.rs
  modules/meteroid/crates/diesel-models/src/extend/mod.rs
  modules/meteroid/crates/diesel-models/src/pgmq.rs
  modules/meteroid/crates/diesel-models/src/query/connectors.rs
  modules/meteroid/crates/diesel-models/src/query/customers.rs
  modules/meteroid/crates/diesel-models/src/query/subscriptions.rs
  modules/meteroid/crates/diesel-models/src/schema.rs
  modules/meteroid/crates/diesel-models/src/subscriptions.rs
  modules/meteroid/crates/hubspot-client/src/deals.rs
  modules/meteroid/crates/hubspot-client/src/model.rs
  modules/meteroid/crates/hubspot-client/src/properties.rs
  modules/meteroid/crates/meteroid-store/src/adapters/payment_service_providers.rs
  modules/meteroid/crates/meteroid-store/src/domain/connectors.rs
  modules/meteroid/crates/meteroid-store/src/domain/customers.rs
  modules/meteroid/crates/meteroid-store/src/domain/outbox_event.rs
  modules/meteroid/crates/meteroid-store/src/domain/pgmq.rs
  modules/meteroid/crates/meteroid-store/src/domain/subscriptions.rs
  modules/meteroid/crates/meteroid-store/src/repositories/connectors.rs
  modules/meteroid/crates/meteroid-store/src/repositories/customers.rs
  modules/meteroid/crates/meteroid-store/src/repositories/subscriptions/mod.rs
  modules/meteroid/crates/meteroid-store/src/repositories/subscriptions/subscriptions_impl.rs
  modules/meteroid/crates/meteroid-store/src/repositories/subscriptions/utils.rs
  modules/meteroid/migrations/diesel/2025-04-06-153949_hubspot_pgmq/down.sql
  modules/meteroid/migrations/diesel/2025-04-06-153949_hubspot_pgmq/up.sql
  modules/meteroid/proto/api/connectors/v1/connectors.proto
  modules/meteroid/proto/api/connectors/v1/models.proto
  modules/meteroid/proto/api/customers/v1/customers.proto
  modules/meteroid/proto/api/subscriptions/v1/subscriptions.proto
  modules/meteroid/src/api/connectors/mapping.rs
  modules/meteroid/src/api/connectors/service.rs
  modules/meteroid/src/api/customers/service.rs
  modules/meteroid/src/api/server.rs
  modules/meteroid/src/api/subscriptions/service.rs
  modules/meteroid/src/api_rest/server.rs
  modules/meteroid/src/bin/scheduler.rs
  modules/meteroid/src/workers/pgmq/hubspot_sync.rs
  modules/meteroid/src/workers/pgmq/mod.rs
  modules/meteroid/src/workers/pgmq/outbox.rs
  modules/meteroid/src/workers/pgmq/processor.rs
  modules/meteroid/src/workers/pgmq/processors.rs
  modules/meteroid/tests/integration/meteroid_it/container.rs
  modules/meteroid/tests/integration/test_customer.rs
Labels: feature

#562 chore: Update rust to 1.86.0
  .github/workflows/ci-rust.yaml
  Cargo.toml
  modules/metering/Dockerfile
  modules/meteroid/api.Dockerfile
  modules/meteroid/crates/meteroid-store/src/crypt.rs
  modules/meteroid/scheduler.Dockerfile
Labels: chore

#563 chore: Use tower BoxError instead of custom BoxError
  crates/common-grpc/src/middleware/client/auth/admin_layer.rs
  crates/common-grpc/src/middleware/client/metric/layer.rs
  crates/common-grpc/src/middleware/server/auth/admin_layer.rs
  crates/common-grpc/src/middleware/server/error_logger/layer.rs
  crates/common-grpc/src/middleware/server/metric/layer.rs
  modules/metering/src/auth.rs
  modules/meteroid/crates/meteroid-middleware/src/server/auth/api_layer.rs
  modules/meteroid/src/api_rest/auth.rs
Labels: chore

#564 chore: Sync subscription status to hubspot
  modules/meteroid/crates/hubspot-client/src/deals.rs
  modules/meteroid/crates/hubspot-client/src/properties.rs
  modules/meteroid/proto/api/connectors/v1/models.proto
  modules/meteroid/proto/api/customers/v1/models.proto
  modules/meteroid/proto/api/subscriptions/v1/models.proto
  modules/meteroid/src/api/connectors/mapping.rs
  modules/meteroid/src/api/customers/mapping.rs
  modules/meteroid/src/api/subscriptions/mapping.rs
  modules/meteroid/src/services/subscription/ext.rs
  modules/meteroid/src/workers/pgmq/hubspot_sync.rs
Labels: chore

#568 feat: Oauth connector for pennylane
  modules/meteroid/crates/diesel-models/src/enums.rs
  modules/meteroid/crates/meteroid-oauth/Cargo.toml
  modules/meteroid/crates/meteroid-oauth/src/config.rs
  modules/meteroid/crates/meteroid-oauth/src/model.rs
  modules/meteroid/crates/meteroid-oauth/src/service.rs
  modules/meteroid/crates/meteroid-store/src/adapters/payment_service_providers.rs
  modules/meteroid/crates/meteroid-store/src/domain/connectors.rs
  modules/meteroid/crates/meteroid-store/src/domain/enums.rs
  modules/meteroid/crates/meteroid-store/src/domain/oauth.rs
  modules/meteroid/crates/meteroid-store/src/domain/organizations.rs
  modules/meteroid/crates/meteroid-store/src/repositories/connectors.rs
  modules/meteroid/crates/meteroid-store/src/repositories/organizations.rs
  modules/meteroid/migrations/diesel/2025-04-24-190555_penylane/down.sql
  modules/meteroid/migrations/diesel/2025-04-24-190555_penylane/up.sql
  modules/meteroid/proto/api/connectors/v1/connectors.proto
  modules/meteroid/proto/api/connectors/v1/models.proto
  modules/meteroid/src/api/connectors/mapping.rs
  modules/meteroid/src/api/connectors/service.rs
  modules/meteroid/src/api_rest/oauth/router.rs
  modules/meteroid/src/api_rest/webhooks/router.rs
Labels: feature

#572 fix: Do not sync billing_iban for pennylane
  modules/meteroid/src/workers/pgmq/pennylane_sync.rs
Labels: bug
