Repository meteroid-oss/meteroid, pull requests merged in 2025-07, with the labels that each got.

#606 feat: Set imputation_dates for pennylane invoice lines
  docker/develop/docker-compose.yml
  modules/meteroid/crates/pennylane-client/src/customer_invoices.rs
  modules/meteroid/src/workers/pgmq/pennylane_sync.rs
  modules/meteroid/tests/integration/metering_it/clickhouse.rs
Labels: feature

#607 fix: Fix billable metric metering view
  modules/metering/src/connectors/clickhouse/mod.rs
  modules/metering/src/connectors/clickhouse/sql/query_meter.rs
  modules/meteroid/src/workers/pgmq/billable_metric_sync.rs
  modules/meteroid/src/workers/pgmq/processors.rs
  modules/meteroid/tests/integration/metering_it/clickhouse.rs
  modules/meteroid/tests/integration/test_metering_ingestion.rs
Labels: bug

#612 chore: add domain whitelist
  modules/metering/src/server.rs
  modules/meteroid/crates/meteroid-store/src/repositories/users.rs
  modules/meteroid/crates/meteroid-store/src/store.rs
  modules/meteroid/src/api/users/service.rs
  modules/meteroid/src/bin/seeder.rs
  modules/meteroid/src/config.rs
  modules/meteroid/src/singletons.rs
  modules/meteroid/tests/integration/meteroid_it/config.rs
  modules/meteroid/tests/integration/meteroid_it/container.rs
  modules/meteroid/tests/integration/test_slot_transaction.rs
  modules/web/web-app/features/auth/components/LoginForm.tsx
Labels: chore

#613 chore: Password length validation
  modules/web/web-app/lib/schemas/me.ts
Labels: chore

#620 feat: add coupons to invoice pdf & ui
  crates/common-domain/src/ids/mod.rs
  modules/meteroid/crates/diesel-models/src/applied_coupons.rs
  modules/meteroid/crates/diesel-models/src/invoices.rs
  modules/meteroid/crates/diesel-models/src/query/applied_coupons.rs
  modules/meteroid/crates/diesel-models/src/query/invoices.rs
  modules/meteroid/crates/diesel-models/src/schema.rs
  modules/meteroid/crates/meteroid-invoicing/examples/typst_invoices.rs
  modules/meteroid/crates/meteroid-invoicing/src/model.rs
  modules/meteroid/crates/meteroid-invoicing/src/typst_render.rs
  modules/meteroid/crates/meteroid-invoicing/templates/invoice.typ
  modules/meteroid/crates/meteroid-invoicing/templates/main.typ
  modules/meteroid/crates/meteroid-seeder/src/random/runner.rs
  modules/meteroid/crates/meteroid-store/src/domain/coupons.rs
  modules/meteroid/crates/meteroid-store/src/domain/invoice_lines.rs
  modules/meteroid/crates/meteroid-store/src/domain/invoices.rs
  modules/meteroid/crates/meteroid-store/src/domain/subscription_coupons.rs
  modules/meteroid/crates/meteroid-store/src/repositories/customers.rs
  modules/meteroid/crates/meteroid-store/src/services/invoices/draft.rs
  modules/meteroid/crates/meteroid-store/src/services/invoices/finalize.rs
  modules/meteroid/crates/meteroid-store/src/services/subscriptions/utils.rs
  modules/meteroid/migrations/diesel/2025-07-17-085142_invoice_coupons/down.sql
  modules/meteroid/migrations/diesel/2025-07-17-085142_invoice_coupons/up.sql
  modules/meteroid/proto/api/invoices/v1/models.proto
  modules/meteroid/src/api/invoices/mapping.rs
  modules/meteroid/src/services/invoice_rendering.rs
  modules/meteroid/tests/integration/e2e.rs
  modules/web/pnpm-lock.yaml
  modules/web/web-app/pages/tenants/invoice/Invoice.tsx
Labels: feature

#619 feat: Rest api create subscription endpoint
  crates/common-domain/src/ids/alias_or.rs
  crates/common-domain/src/ids/mod.rs
  modules/meteroid/crates/diesel-models/src/query/coupons.rs
  modules/meteroid/crates/meteroid-store/src/repositories/coupons.rs
  modules/meteroid/src/api_rest/customers/router.rs
  modules/meteroid/src/api_rest/model.rs
  modules/meteroid/src/api_rest/subscriptions/mapping.rs
  modules/meteroid/src/api_rest/subscriptions/mod.rs
  modules/meteroid/src/api_rest/subscriptions/model.rs
  modules/meteroid/src/api_rest/subscriptions/router.rs
  modules/meteroid/tests/integration/meteroid_it/container.rs
  modules/meteroid/tests/integration/test_auth_api_key.rs
  spec/api/v1/openapi.json
Labels: feature

#622 chore: Use a single format for rest enums
  modules/meteroid/src/api_rest/model.rs
  modules/meteroid/src/api_rest/plans/model.rs
  modules/meteroid/src/api_rest/subscriptions/mapping.rs
  modules/meteroid/src/api_rest/subscriptions/model.rs
  spec/api/v1/openapi.json
Labels: chore
