Repository meteroid-oss/meteroid, pull requests merged in 2025-01, with the labels that each got.

#441 chore: Happy new 2025 year
  README.md
  modules/web/web-app/features/dashboard/Dashboard.tsx
Labels: chore

#448 chore: Fix rust lint
  crates/kafka/src/config.rs
  modules/meteroid/crates/meteroid-invoicing/Cargo.toml
  modules/meteroid/crates/meteroid-invoicing/src/html_render.rs
Labels: chore

#449 chore: Align currencies
  modules/meteroid/Cargo.toml
  modules/meteroid/src/api_rest/currencies/model.rs
  modules/meteroid/src/constants.rs
  modules/meteroid/src/services/currency_rates.rs
  spec/api/v1/openapi.json
Labels: chore

#452 chore: Add validation for TieredAndVolume
  modules/meteroid/src/api/subscriptions/mapping.rs
Labels: chore

#453 feat: Add basic mailer functionality
  .env.example
  Cargo.toml
  modules/meteroid/Cargo.toml
  modules/meteroid/src/config.rs
  modules/meteroid/src/errors.rs
  modules/meteroid/src/services/mailer.rs
  modules/meteroid/src/services/mod.rs
  modules/meteroid/tests/integration/meteroid_it/config.rs
Labels: feature

#454 feat: Add reset password grpc api
  .env.example
  Cargo.toml
  modules/meteroid/Cargo.toml
  modules/meteroid/crates/diesel-models/src/query/users.rs
  modules/meteroid/crates/meteroid-mailer/Cargo.toml
  modules/meteroid/crates/meteroid-mailer/src/config.rs
  modules/meteroid/crates/meteroid-mailer/src/errors.rs
  modules/meteroid/crates/meteroid-mailer/src/lib.rs
  modules/meteroid/crates/meteroid-mailer/src/model.rs
  modules/meteroid/crates/meteroid-mailer/src/service.rs
  modules/meteroid/crates/meteroid-mailer/src/template.rs
  modules/meteroid/crates/meteroid-mailer/templates/reset_password_link.html
  modules/meteroid/crates/meteroid-store/Cargo.toml
  modules/meteroid/crates/meteroid-store/src/errors.rs
  modules/meteroid/crates/meteroid-store/src/repositories/users.rs
  modules/meteroid/crates/meteroid-store/src/store.rs
  modules/meteroid/proto/api/users/v1/users.proto
  modules/meteroid/src/api/users/error.rs
  modules/meteroid/src/api/users/service.rs
  modules/meteroid/src/bin/seeder.rs
  modules/meteroid/src/bin/server.rs
  modules/meteroid/src/config.rs
  modules/meteroid/src/errors.rs
  modules/meteroid/src/services/mailer.rs
  modules/meteroid/src/services/mod.rs
  modules/meteroid/src/singletons.rs
  modules/meteroid/tests/integration/meteroid_it/config.rs
  modules/meteroid/tests/integration/meteroid_it/container.rs
  modules/meteroid/tests/integration/test_slot_transaction.rs
  modules/meteroid/tests/integration/test_workers.rs
Labels: feature

#455 feat: Add bank accounts
  crates/common-eventbus/src/lib.rs
  modules/meteroid/crates/diesel-models/src/bank_accounts.rs
  modules/meteroid/crates/diesel-models/src/configs.rs
  modules/meteroid/crates/diesel-models/src/enums.rs
  modules/meteroid/crates/diesel-models/src/invoicing_entities.rs
  modules/meteroid/crates/diesel-models/src/lib.rs
  modules/meteroid/crates/diesel-models/src/query/bank_accounts.rs
  modules/meteroid/crates/diesel-models/src/query/invoicing_entities.rs
  modules/meteroid/crates/diesel-models/src/query/mod.rs
  modules/meteroid/crates/diesel-models/src/schema.rs
  modules/meteroid/crates/meteroid-grpc/build.rs
  modules/meteroid/crates/meteroid-grpc/src/lib.rs
  modules/meteroid/crates/meteroid-store/src/domain/bank_accounts.rs
  modules/meteroid/crates/meteroid-store/src/domain/configs.rs
  modules/meteroid/crates/meteroid-store/src/domain/enums.rs
  modules/meteroid/crates/meteroid-store/src/domain/invoicing_entities.rs
  modules/meteroid/crates/meteroid-store/src/domain/mod.rs
  modules/meteroid/crates/meteroid-store/src/repositories/bank_accounts.rs
  modules/meteroid/crates/meteroid-store/src/repositories/invoicing_entities.rs
  modules/meteroid/crates/meteroid-store/src/repositories/mod.rs
  modules/meteroid/crates/meteroid-store/src/utils/local_id.rs
  modules/meteroid/migrations/diesel/2025-01-20-000001_bank_accounts/down.sql
  modules/meteroid/migrations/diesel/2025-01-20-000001_bank_accounts/up.sql
  modules/meteroid/proto/api/bankaccounts/v1/bankaccounts.proto
  modules/meteroid/proto/api/bankaccounts/v1/models.proto
  modules/meteroid/proto/api/invoicingentities/v1/invoicingentities.proto
  modules/meteroid/src/api/bankaccounts/error.rs
  modules/meteroid/src/api/bankaccounts/mapping.rs
  modules/meteroid/src/api/bankaccounts/mod.rs
  modules/meteroid/src/api/bankaccounts/service.rs
  modules/meteroid/src/api/invoicingentities/service.rs
  modules/meteroid/src/api/mod.rs
  modules/meteroid/src/api/server.rs
  modules/meteroid/src/workers/kafka/processor.rs
Labels: feature

#456 feat: Available currencies
  docker/develop/data/seed.sql
  modules/meteroid/crates/diesel-models/src/errors.rs
  modules/meteroid/crates/diesel-models/src/query/stats.rs
  modules/meteroid/crates/diesel-models/src/query/tenants.rs
  modules/meteroid/crates/diesel-models/src/schema.rs
  modules/meteroid/crates/diesel-models/src/tenants.rs
  modules/meteroid/crates/meteroid-grpc/src/lib.rs
  modules/meteroid/crates/meteroid-store/src/domain/tenants.rs
  modules/meteroid/crates/meteroid-store/src/repositories/plans.rs
  modules/meteroid/crates/meteroid-store/src/repositories/stats.rs
  modules/meteroid/crates/meteroid-store/src/repositories/tenants.rs
  modules/meteroid/migrations/diesel/2025-01-20-000001_bank_accounts/down.sql
  modules/meteroid/migrations/diesel/2025-01-20-000001_bank_accounts/up.sql
  modules/meteroid/proto/api/tenants/v1/models.proto
  modules/meteroid/proto/api/tenants/v1/tenants.proto
  modules/meteroid/src/api/tenants/mapping.rs
  modules/meteroid/src/api/tenants/service.rs
  modules/meteroid/tests/data/0_minimal.sql
  modules/meteroid/tests/integration/test_basic.rs
  modules/meteroid/tests/integration/test_tenant.rs
Labels: feature

#461 chore(ARM): Github now supports arm runners
  .github/workflows/docker.yaml
Labels: chore

#462 chore: Update opentelemetry
  docker/develop/docker-compose.yml
  docker/develop/opensearch-dashboards/Dockerfile
  docker/develop/opensearch-dashboards/opensearch_dashboards.yml
  docker/develop/volume/grafana/grafana.ini
  docker/develop/volume/grafana/provisioning/dashboards/otel/demo-dashboard.json
  docker/develop/volume/grafana/provisioning/dashboards/otel/opentelemetry-collector-data-flow.json
  docker/develop/volume/grafana/provisioning/dashboards/otel/opentelemetry-collector.json
  docker/develop/volume/grafana/provisioning/dashboards/otel/spanmetrics-dashboard.json
  docker/develop/volume/grafana/provisioning/datasources/opensearch.yaml
  docker/develop/volume/opensearch/data-prepper-config.yaml
  docker/develop/volume/opensearch/pipelines.yaml
  docker/develop/volume/opensearch/pipelines_disabled_simplified.yaml
  docker/develop/volume/otelcollector/otelcol-config.yml
  docker/develop/volume/prometheus/prometheus-config.yaml
Labels: chore

#463 feat: Export logs to loki
  Cargo.toml
  crates/common-logging/Cargo.toml
  crates/common-logging/src/init.rs
  docker/develop/docker-compose.yml
  docker/develop/volume/grafana/provisioning/datasources/loki.yaml
  docker/develop/volume/loki/local-config.yaml
  docker/develop/volume/otelcollector/otelcol-config.yml
Labels: feature

#471 feat: Svix webhook portal access
  Cargo.toml
  modules/meteroid/crates/meteroid-store/Cargo.toml
  modules/meteroid/crates/meteroid-store/src/domain/enums.rs
  modules/meteroid/crates/meteroid-store/src/domain/misc.rs
  modules/meteroid/crates/meteroid-store/src/domain/webhooks.rs
  modules/meteroid/crates/meteroid-store/src/repositories/webhooks.rs
  modules/meteroid/crates/meteroid-store/src/store.rs
  modules/meteroid/proto/api/webhooksout/v1/webhooksout.proto
  modules/meteroid/src/api/webhooksout/service.rs
  modules/meteroid/src/workers/kafka/outbox.rs
  modules/meteroid/src/workers/kafka/webhook.rs
Labels: feature

#472 fix: Allow configuring env in frontend docker
  modules/web/web-app/Dockerfile
  modules/web/web-app/index.html
  modules/web/web-app/init-docker-env.sh
  modules/web/web-app/lib/env.ts
  modules/web/web-app/nginx-gzip.conf
  modules/web/web-app/nginx.conf
  modules/web/web-app/public/apple-touch-icon.png
  modules/web/web-app/public/favicon-96x96.png
  modules/web/web-app/public/favicon.ico
  modules/web/web-app/public/favicon.svg
  modules/web/web-app/public/site.webmanifest
  modules/web/web-app/public/web-app-manifest-192x192.png
  modules/web/web-app/public/web-app-manifest-512x512.png
Labels: bug

#473 fix: tenant slug should be unique locally
  modules/meteroid/migrations/diesel/2025-01-30-235223_fix_tenant_constraint/down.sql
  modules/meteroid/migrations/diesel/2025-01-30-235223_fix_tenant_constraint/up.sql
  modules/meteroid/tests/integration/meteroid_it/container.rs
  modules/web/web-app/lib/env.ts
Labels: bug

#474 chore: health endpoint & improve docker tags
  .github/workflows/docker.yaml
  modules/meteroid/src/api_rest/server.rs
Labels: chore

#475 chore: attempt to clean docker meta
  .github/workflows/docker.yaml
Labels: chore
