Repository meteroid-oss/meteroid, pull requests merged in 2025-09, with the labels that each got.

#682 feat: Signoz docker dev deployment
  docker/develop/docker-compose-telemetry-signoz.yml
  docker/develop/signoz/clickhouse/cluster.ha.xml
  docker/develop/signoz/clickhouse/cluster.xml
  docker/develop/signoz/clickhouse/config.xml
  docker/develop/signoz/clickhouse/custom-function.xml
  docker/develop/signoz/clickhouse/storage.xml
  docker/develop/signoz/clickhouse/user_scripts/.gitkeep
  docker/develop/signoz/clickhouse/user_scripts/histogramQuantile
  docker/develop/signoz/clickhouse/users.xml
  docker/develop/signoz/dashboards/.gitkeep
  docker/develop/signoz/dashboards/Grpc API.json
  docker/develop/signoz/otel-collector-config.yaml
  docker/develop/signoz/otel-collector-opamp-config.yaml
  docker/develop/signoz/prometheus.yml
Labels: feature

#700 fix: Fix invoice line dates
  modules/meteroid/crates/pennylane-client/src/customer_invoices.rs
  modules/meteroid/crates/pennylane-client/src/customers.rs
  modules/web/web-app/lib/schemas/invoices.ts
  modules/web/web-app/pages/tenants/invoice/invoiceCreate.tsx
Labels: bug

#701 chore: Display invoice discount
  modules/meteroid/crates/meteroid-invoicing/examples/typst_invoices.rs
  modules/meteroid/crates/meteroid-invoicing/l10n/en-US/invoice.ftl
  modules/meteroid/crates/meteroid-invoicing/l10n/fr-FR/invoice.ftl
  modules/meteroid/crates/meteroid-invoicing/src/model.rs
  modules/meteroid/crates/meteroid-invoicing/src/typst_render.rs
  modules/meteroid/crates/meteroid-invoicing/templates/invoice.typ
  modules/meteroid/crates/meteroid-invoicing/templates/main.typ
  modules/meteroid/crates/meteroid-invoicing/tests/typst_validation.rs
  modules/meteroid/src/api/invoices/service.rs
  modules/meteroid/src/services/invoice_rendering.rs
Labels: chore

#705 chore: Multiple bug fixes
  modules/meteroid/crates/meteroid-invoicing/src/model.rs
  modules/meteroid/crates/meteroid-invoicing/src/typst_render.rs
  modules/meteroid/src/services/invoice_rendering.rs
  modules/web/web-app/features/settings/tabs/CompanyTab.tsx
  modules/web/web-app/pages/tenants/customer/customer.tsx
Labels: chore

#707 feat: Quotes screens & base apis
  crates/common-domain/src/ids/mod.rs
  crates/common-grpc/src/middleware/server/auth/mod.rs
  modules/meteroid/crates/diesel-models/src/enums.rs
  modules/meteroid/crates/diesel-models/src/lib.rs
  modules/meteroid/crates/diesel-models/src/query/mod.rs
  modules/meteroid/crates/diesel-models/src/query/quotes.rs
  modules/meteroid/crates/diesel-models/src/quotes.rs
  modules/meteroid/crates/diesel-models/src/schema.rs
  modules/meteroid/crates/meteroid-grpc/build.rs
  modules/meteroid/crates/meteroid-grpc/src/lib.rs
  modules/meteroid/crates/meteroid-middleware/src/server/auth/strategies/portal_jwt_strategy.rs
  modules/meteroid/crates/meteroid-store/src/domain/enums.rs
  modules/meteroid/crates/meteroid-store/src/domain/macros.rs
  modules/meteroid/crates/meteroid-store/src/domain/mod.rs
  modules/meteroid/crates/meteroid-store/src/domain/quotes.rs
  modules/meteroid/crates/meteroid-store/src/jwt_claims.rs
  modules/meteroid/crates/meteroid-store/src/repositories/mod.rs
  modules/meteroid/crates/meteroid-store/src/repositories/quotes.rs
  modules/meteroid/migrations/diesel/2025-09-15-114223_quotes/down.sql
  modules/meteroid/migrations/diesel/2025-09-15-114223_quotes/up.sql
  modules/meteroid/proto/api/invoicingentities/v1/models.proto
  modules/meteroid/proto/api/quotes/v1/models.proto
  modules/meteroid/proto/api/quotes/v1/quotes.proto
  modules/meteroid/proto/portal/quotes/v1/models.proto
  modules/meteroid/proto/portal/quotes/v1/quotes.proto
  modules/meteroid/src/api/invoicingentities/mapping.rs
  modules/meteroid/src/api/mod.rs
  modules/meteroid/src/api/portal/mod.rs
  modules/meteroid/src/api/portal/quotes/error.rs
  modules/meteroid/src/api/portal/quotes/mod.rs
  modules/meteroid/src/api/portal/quotes/service.rs
  modules/meteroid/src/api/quotes/error.rs
  modules/meteroid/src/api/quotes/mapping.rs
  modules/meteroid/src/api/quotes/mod.rs
  modules/meteroid/src/api/quotes/service.rs
  modules/meteroid/src/api/server.rs
  modules/meteroid/src/api/subscriptions/mapping.rs
  modules/meteroid/src/api_rest/files/router.rs
  modules/web/packages/ui/src/components/form/date-form-field.tsx
  modules/web/packages/ui/src/components/form/index.ts
  modules/web/pnpm-lock.yaml
  modules/web/web-app/buf.gen.yaml
  modules/web/web-app/features/quotes/QuotePortalView.tsx
  modules/web/web-app/features/quotes/QuotePriceComponentsWrapper.tsx
  modules/web/web-app/features/quotes/QuoteView.tsx
  modules/web/web-app/features/subscriptions/pricecomponents/CreateSubscriptionPriceComponents.tsx
  modules/web/web-app/features/subscriptions/pricecomponents/PriceComponentsLogic.tsx
  modules/web/web-app/features/subscriptions/pricecomponents/SubscriptionPricingTable.tsx
  modules/web/web-app/features/subscriptions/utils/fees.ts
  modules/web/web-app/lib/utils/params.ts
  modules/web/web-app/package.json
  modules/web/web-app/pages/portal/quote.tsx
  modules/web/web-app/pages/tenants/quotes/CreateQuote.tsx
  modules/web/web-app/pages/tenants/quotes/Quote.tsx
  modules/web/web-app/pages/tenants/quotes/Quotes.tsx
  modules/web/web-app/pages/tenants/quotes/index.tsx
  modules/web/web-app/pages/tenants/subscription/create/StepReviewAndCreate.tsx
  modules/web/web-app/pages/tenants/subscription/subscription.tsx
  modules/web/web-app/router/portal.tsx
  modules/web/web-app/router/tenant/billing.tsx
Labels: feature

#709 fix: Display default price component in quote preview
  modules/web/web-app/features/quotes/QuoteView.tsx
  modules/web/web-app/pages/tenants/quotes/CreateQuote.tsx
Labels: bug

#712 feat: Void invoice + mark invoice as uncollectible
  modules/meteroid/crates/diesel-models/src/invoices.rs
  modules/meteroid/crates/diesel-models/src/query/invoices.rs
  modules/meteroid/crates/diesel-models/src/schema.rs
  modules/meteroid/crates/meteroid-store/src/domain/invoices.rs
  modules/meteroid/crates/meteroid-store/src/repositories/invoices.rs
  modules/meteroid/migrations/diesel/2025-09-19-190349_invoice_actions/down.sql
  modules/meteroid/migrations/diesel/2025-09-19-190349_invoice_actions/up.sql
  modules/meteroid/proto/api/invoices/v1/invoices.proto
  modules/meteroid/proto/api/invoices/v1/models.proto
  modules/meteroid/src/api/invoices/mapping.rs
  modules/meteroid/src/api/invoices/service.rs
  modules/web/web-app/features/settings/integrations/FinalizeInvoiceModal.tsx
  modules/web/web-app/pages/tenants/invoice/Invoice.tsx
  modules/web/web-app/pages/tenants/invoice/InvoiceConfirmationDialog.tsx
Labels: feature

#714 chore: Upgrade rust to 1.90
  .github/workflows/ci-rust.yaml
  Cargo.toml
  modules/adapters/openstack/src/events.rs
  modules/metering/Dockerfile
  modules/meteroid/api.Dockerfile
  modules/meteroid/scheduler.Dockerfile
  modules/meteroid/src/api/plans/mapping.rs
Labels: chore

#721 fix: ch migration
  modules/metering/migrations/refinery/V3__kafka_sasl_auth.rs
Labels: bug

#722 fix: replicated ch engines
  modules/metering/migrations/refinery/V3__kafka_sasl_auth.rs
  modules/metering/migrations/refinery/V3__reset_replicated_and_kafka_auth.rs
  modules/metering/src/config.rs
  modules/metering/src/migrations.rs
  modules/meteroid/tests/integration/metering_it/config.rs
Labels: bug

#724 chore: add cluster aware ch migrations
  modules/metering/src/migrations.rs
Labels: chore

#725 chore: add logs to meter query
  .github/workflows/ci-rust.yaml
  modules/metering/src/connectors/clickhouse/mod.rs
Labels: chore

#727 fix: add plan currency to draft api
  modules/meteroid/proto/api/plans/v1/plans.proto
  modules/meteroid/src/api/plans/service.rs
  modules/meteroid/tests/integration/e2e.rs
  modules/meteroid/tests/integration/test_basic.rs
  modules/meteroid/tests/integration/test_plan.rs
  modules/web/web-app/features/plans/create/details/DetailsForm.tsx
  modules/web/web-app/lib/schemas/plans.ts
Labels: bug

#728 fix: Align positioning of event code
  modules/web/web-app/features/events/EventsPage.tsx
Labels: bug

#732 feat: add metrics view and archive
  modules/meteroid/crates/diesel-models/src/query/billable_metrics.rs
  modules/meteroid/crates/meteroid-store/src/repositories/billable_metrics.rs
  modules/meteroid/proto/api/billablemetrics/v1/billablemetrics.proto
  modules/meteroid/src/api/billablemetrics/service.rs
  modules/web/web-app/features/productCatalog/metrics/AggregationSection.tsx
  modules/web/web-app/features/productCatalog/metrics/ProductMetricsEditPanel.tsx
  modules/web/web-app/features/productCatalog/metrics/ProductMetricsPageHeader.tsx
  modules/web/web-app/features/productCatalog/metrics/ProductMetricsTable.tsx
  modules/web/web-app/features/productCatalog/metrics/SegmentationMatrixSection.tsx
  modules/web/web-app/features/productCatalog/metrics/UnitConversionSection.tsx
  modules/web/web-app/lib/utils/params.ts
  modules/web/web-app/pages/tenants/catalog/productMetricDetail.tsx
  modules/web/web-app/pages/tenants/catalog/productMetrics.tsx
  modules/web/web-app/router/tenant/catalog.tsx
Labels: feature

#731 chore: Refresh only usage based invoice lines
  modules/meteroid/crates/meteroid-store/src/services/edge.rs
  modules/meteroid/crates/meteroid-store/src/services/invoice_lines/invoice_lines.rs
  modules/meteroid/crates/meteroid-store/src/services/invoices/draft.rs
  modules/meteroid/crates/meteroid-store/src/services/invoices/refresh.rs
Labels: chore

#735 fix: invoice svg preview breaks on long invoice
  modules/meteroid/crates/meteroid-invoicing/src/svg.rs
  modules/meteroid/proto/api/invoices/v1/invoices.proto
  modules/meteroid/src/api/invoices/service.rs
  modules/meteroid/src/api_rest/files/router.rs
  modules/meteroid/src/services/invoice_rendering.rs
  modules/web/web-app/pages/tenants/invoice/Invoice.tsx
  modules/web/web-app/pages/tenants/invoice/invoiceCreate.tsx
Labels: bug

#744 chore: Cleanup quote proto files
  modules/meteroid/proto/api/quotes/v1/models.proto
  modules/meteroid/proto/portal/quotes/v1/models.proto
  modules/meteroid/proto/portal/quotes/v1/quotes.proto
Labels: chore
