Repository meteroid-oss/meteroid, pull requests merged in 2025-03, with the labels that each got.

#514 chore: docker compose for fe
  CONTRIBUTING.md
  docker/develop/for-frontends/docker-compose-light.yml
Labels: chore

#515 feat: Update auth flow with email validation
  .env.example
  crates/common-domain/src/auth.rs
  crates/common-domain/src/lib.rs
  crates/common-grpc/src/middleware/common/jwt.rs
  crates/common-grpc/src/middleware/common/mod.rs
  modules/meteroid/crates/diesel-models/src/query/organizations.rs
  modules/meteroid/crates/meteroid-mailer/src/model.rs
  modules/meteroid/crates/meteroid-mailer/src/service.rs
  modules/meteroid/crates/meteroid-mailer/src/template.rs
  modules/meteroid/crates/meteroid-mailer/templates/email_validation_link.html
  modules/meteroid/crates/meteroid-middleware/src/server/auth/api_layer.rs
  modules/meteroid/crates/meteroid-middleware/src/server/auth/strategies/jwt_strategy.rs
  modules/meteroid/crates/meteroid-oauth/src/config.rs
  modules/meteroid/crates/meteroid-oauth/src/service.rs
  modules/meteroid/crates/meteroid-store/src/domain/organizations.rs
  modules/meteroid/crates/meteroid-store/src/domain/users.rs
  modules/meteroid/crates/meteroid-store/src/repositories/organizations.rs
  modules/meteroid/crates/meteroid-store/src/repositories/users.rs
  modules/meteroid/crates/meteroid-store/src/store.rs
  modules/meteroid/proto/api/instance/v1/instance.proto
  modules/meteroid/proto/api/users/v1/users.proto
  modules/meteroid/src/api/instance/service.rs
  modules/meteroid/src/api/users/service.rs
  modules/meteroid/src/bin/seeder.rs
  modules/meteroid/src/bin/server.rs
  modules/meteroid/src/config.rs
  modules/meteroid/src/singletons.rs
  modules/meteroid/tests/integration/meteroid_it/container.rs
  modules/meteroid/tests/integration/test_idempotency_cache.rs
  modules/meteroid/tests/integration/test_slot_transaction.rs
  modules/meteroid/tests/integration/test_user.rs
  modules/meteroid/tests/integration/test_workers.rs
  modules/web/web-app/features/auth/components/RegistrationForm.tsx
Labels: feature

#516 chore: rotate encoded ids bytes to break timestamp prefix
  crates/common-domain/src/ids/macros.rs
  crates/common-domain/src/ids/mod.rs
Labels: chore

#519 fix: Fix diesel schema
  modules/meteroid/crates/diesel-models/src/schema.rs
  modules/meteroid/crates/diesel-models/src/subscriptions.rs
Labels: bug

#524 feat: Hubspot oauth connect
  .env.example
  modules/meteroid/crates/diesel-models/src/enums.rs
  modules/meteroid/crates/diesel-models/src/oauth_verifiers.rs
  modules/meteroid/crates/diesel-models/src/query/tenants.rs
  modules/meteroid/crates/diesel-models/src/schema.rs
  modules/meteroid/crates/diesel-models/src/tenants.rs
  modules/meteroid/crates/meteroid-oauth/src/config.rs
  modules/meteroid/crates/meteroid-oauth/src/errors.rs
  modules/meteroid/crates/meteroid-oauth/src/model.rs
  modules/meteroid/crates/meteroid-oauth/src/service.rs
  modules/meteroid/crates/meteroid-store/src/adapters/payment_service_providers.rs
  modules/meteroid/crates/meteroid-store/src/domain/connectors.rs
  modules/meteroid/crates/meteroid-store/src/domain/enums.rs
  modules/meteroid/crates/meteroid-store/src/domain/mod.rs
  modules/meteroid/crates/meteroid-store/src/domain/oauth.rs
  modules/meteroid/crates/meteroid-store/src/domain/organizations.rs
  modules/meteroid/crates/meteroid-store/src/domain/tenants.rs
  modules/meteroid/crates/meteroid-store/src/repositories/connectors.rs
  modules/meteroid/crates/meteroid-store/src/repositories/customer_payment_methods.rs
  modules/meteroid/crates/meteroid-store/src/repositories/mod.rs
  modules/meteroid/crates/meteroid-store/src/repositories/oauth.rs
  modules/meteroid/crates/meteroid-store/src/repositories/organizations.rs
  modules/meteroid/crates/meteroid-store/src/repositories/subscriptions/payment_method.rs
  modules/meteroid/crates/meteroid-store/src/repositories/tenants.rs
  modules/meteroid/crates/meteroid-store/src/repositories/users.rs
  modules/meteroid/migrations/diesel/2025-03-15-194617_hubspot/down.sql
  modules/meteroid/migrations/diesel/2025-03-15-194617_hubspot/up.sql
  modules/meteroid/proto/api/connectors/v1/connectors.proto
  modules/meteroid/proto/api/connectors/v1/models.proto
  modules/meteroid/proto/api/instance/v1/instance.proto
  modules/meteroid/src/api/connectors/mapping.rs
  modules/meteroid/src/api/connectors/service.rs
  modules/meteroid/src/api/instance/service.rs
  modules/meteroid/src/api_rest/oauth/router.rs
  modules/meteroid/src/api_rest/webhooks/router.rs
Labels: feature

#527 chore: frontend lint cleanup
  .env.example
  .vscode/extensions.json
  CONTRIBUTING.md
  docker/develop/for-frontends/docker-compose-lite.yml
  k8s/meteroid/templates/web-deployment.yaml
  modules/meteroid/crates/meteroid-invoicing/pnpm-lock.yaml
  modules/web/package.json
  modules/web/packages/common/package.json
  modules/web/packages/common/pnpm-lock.yaml
  modules/web/packages/common/src/env/preprocessors.ts
  modules/web/packages/config/package.json
  modules/web/packages/config/pnpm-lock.yaml
  modules/web/packages/eslint-config-meteroid/package.json
  modules/web/packages/eslint-config-meteroid/pnpm-lock.yaml
  modules/web/packages/foundation/package.json
  modules/web/packages/foundation/pnpm-lock.yaml
  modules/web/packages/icons/package.json
  modules/web/packages/icons/pnpm-lock.yaml
  modules/web/packages/tsconfig/pnpm-lock.yaml
  modules/web/packages/ui/package.json
  modules/web/packages/ui/pnpm-lock.yaml
  modules/web/pnpm-lock.yaml
  modules/web/pnpm-workspace.yaml
  modules/web/web-app/components/SidebarMenu/components/Item.tsx
  modules/web/web-app/components/layouts/TenantLayout/NavigationBar/components/Items/components/Item/Item.tsx
  modules/web/web-app/features/productCatalog/generic/CatalogEditPanel.tsx
  modules/web/web-app/hooks/useZodForm.tsx
  modules/web/web-app/package.json
  modules/web/web-app/pages/auth/validate-email.tsx
  modules/web/web-app/pnpm-lock.yaml
  modules/web/web-app/router/anonymous.tsx
Labels: chore

#526 fix: Fix hubspot redirect url in case of successful connection
  modules/meteroid/crates/meteroid-store/src/domain/oauth.rs
  modules/meteroid/crates/meteroid-store/src/repositories/connectors.rs
  modules/meteroid/src/api/connectors/service.rs
  modules/meteroid/src/api/utils.rs
  modules/meteroid/src/api_rest/oauth/router.rs
Labels: bug

#530 chore: Polish Oauth service
  Cargo.toml
  modules/meteroid/crates/diesel-models/src/query/connectors.rs
  modules/meteroid/crates/meteroid-oauth/src/model.rs
  modules/meteroid/crates/meteroid-oauth/src/service.rs
  modules/meteroid/crates/meteroid-store/src/errors.rs
  modules/meteroid/crates/meteroid-store/src/repositories/connectors.rs
  modules/meteroid/crates/meteroid-store/src/repositories/oauth.rs
  modules/meteroid/src/api/connectors/service.rs
  modules/meteroid/src/api_rest/oauth/router.rs
Labels: chore

#536 fix: new lint to remove to_string in debug_query
  modules/meteroid/crates/diesel-models/src/query/add_ons.rs
  modules/meteroid/crates/diesel-models/src/query/api_tokens.rs
  modules/meteroid/crates/diesel-models/src/query/applied_coupons.rs
  modules/meteroid/crates/diesel-models/src/query/bank_accounts.rs
  modules/meteroid/crates/diesel-models/src/query/bi.rs
  modules/meteroid/crates/diesel-models/src/query/billable_metrics.rs
  modules/meteroid/crates/diesel-models/src/query/connectors.rs
  modules/meteroid/crates/diesel-models/src/query/coupons.rs
  modules/meteroid/crates/diesel-models/src/query/customer_balance_txs.rs
  modules/meteroid/crates/diesel-models/src/query/customer_connections.rs
  modules/meteroid/crates/diesel-models/src/query/customer_payment_methods.rs
  modules/meteroid/crates/diesel-models/src/query/customers.rs
  modules/meteroid/crates/diesel-models/src/query/historical_rates_from_usd.rs
  modules/meteroid/crates/diesel-models/src/query/invoices.rs
  modules/meteroid/crates/diesel-models/src/query/invoicing_entities.rs
  modules/meteroid/crates/diesel-models/src/query/oauth_verifiers.rs
  modules/meteroid/crates/diesel-models/src/query/organization_members.rs
  modules/meteroid/crates/diesel-models/src/query/organizations.rs
  modules/meteroid/crates/diesel-models/src/query/outbox_event.rs
  modules/meteroid/crates/diesel-models/src/query/payment_transactions.rs
  modules/meteroid/crates/diesel-models/src/query/plan_versions.rs
  modules/meteroid/crates/diesel-models/src/query/plans.rs
  modules/meteroid/crates/diesel-models/src/query/price_components.rs
  modules/meteroid/crates/diesel-models/src/query/product_families.rs
  modules/meteroid/crates/diesel-models/src/query/products.rs
  modules/meteroid/crates/diesel-models/src/query/schedules.rs
  modules/meteroid/crates/diesel-models/src/query/slot_transactions.rs
  modules/meteroid/crates/diesel-models/src/query/stats.rs
  modules/meteroid/crates/diesel-models/src/query/subscription_add_ons.rs
  modules/meteroid/crates/diesel-models/src/query/subscription_components.rs
  modules/meteroid/crates/diesel-models/src/query/subscription_events.rs
  modules/meteroid/crates/diesel-models/src/query/subscriptions.rs
  modules/meteroid/crates/diesel-models/src/query/tenants.rs
  modules/meteroid/crates/diesel-models/src/query/users.rs
  modules/meteroid/crates/diesel-models/src/query/webhooks.rs
  modules/meteroid/crates/meteroid-store/src/repositories/webhooks.rs
  modules/meteroid/src/seeder/runner.rs
Labels: bug

#537 feat: add runtime scenario seeding
  Cargo.toml
  docker/develop/docker-compose-lite.yml
  docker/develop/docker-compose-telemetry.yml
  docker/develop/docker-compose.yml
  modules/meteroid/Cargo.toml
  modules/meteroid/crates/meteroid-seeder/Cargo.toml
  modules/meteroid/crates/meteroid-seeder/src/lib.rs
  modules/meteroid/crates/meteroid-seeder/src/presets/mod.rs
  modules/meteroid/crates/meteroid-seeder/src/presets/runner.rs
  modules/meteroid/crates/meteroid-seeder/src/presets/scenarios/domain.rs
  modules/meteroid/crates/meteroid-seeder/src/presets/scenarios/mod.rs
  modules/meteroid/crates/meteroid-seeder/src/presets/scenarios/simple.rs
  modules/meteroid/crates/meteroid-seeder/src/random/domain.rs
  modules/meteroid/crates/meteroid-seeder/src/random/errors.rs
  modules/meteroid/crates/meteroid-seeder/src/random/growth.rs
  modules/meteroid/crates/meteroid-seeder/src/random/mod.rs
  modules/meteroid/crates/meteroid-seeder/src/random/runner.rs
  modules/meteroid/crates/meteroid-seeder/src/store_interface.rs
  modules/meteroid/crates/meteroid-seeder/src/utils.rs
  modules/meteroid/crates/meteroid-store/src/domain/enums.rs
  modules/meteroid/crates/meteroid-store/src/domain/subscriptions.rs
  modules/meteroid/src/api/tenants/service.rs
  modules/meteroid/src/bin/seeder.rs
  modules/meteroid/src/lib.rs
  modules/web/web-app/features/dashboard/Dashboard.tsx
  modules/web/web-app/pages/tenants/new.tsx
Labels: feature
